---
title: "Bats say: let California Burn"
author: "Derek Corcoran"
date: "May 5, 2016"
output: word_document
bibliography: bibliography.bib
---

#Introduction

Recent studies have shown that there has been an increase in both fire frequency and severity in all the West Coast of the United States and in the Sierra Nevada Range in Particular [@miller2009quantitative; @westerling2006warming]. The increase in the fire frequency is both due to human activity [@syphard2007human] and global change [@lenihan2003climate].  

It is highly unlikely that this increment is reverted and thus it is very important to understand the impact of high intensity fires in the forest ecosystem. It has been predicted that fires will increase in frequency and area in the whole western coast of the United Sates as predicted through year 2100 [@liu2016direct]. In particular in Northern Sierra Nevada it has been established that fire suppression has homogenized the environments with a higher representation of fire intolerant species [@beaty2008fire]. There is increasing evidence of a higher frequency of wildfires and an increase of area burned annually in Sierra Nevada [@miller2009quantitative] Specifically at higher elevations [@keeley2015different; @schwartz2015increasing]. 

The Sierra Nevada Bioregion is dominated by mixed-conifer forest with some redfire forest and evergreen conifer areas [@steel2015fire]. With a fuel-limited fire regime [@steel2015fire]. It has a Mediterranean climate with dry and warm summers and cool wet winters. The highest precipitation in the state of California corresponds to our study site in the northern limit of the Sierra Nevada [@van2006sierra]. Changes in the ecosystems and communities along the Sierra Nevada mainly follow a west-east gradient of altitude and rainfall due to orographic rains coming from the pacific coast, rainfall increases with altitude and as it drops to the east we find the driest environments. The most common environment is the lower montane forest [@van2006sierra]. The dominant species of this community are the Jeffrey Pine (*Pinus jeffreyi*) and Ponderosa Pine (*Pinus ponderosa*).

Bats are one of the most diverse group of mammals with around 1240 species [@tudge2000variety; @schipper2008status], second only in number of species to rodents. The distinctive characteristic of this group is their ability to fly. They live in every continent but Antarctica. Most of them are insectivores, but some of them are pollinators and some very specialized species are hematofagous or carnivorous [@kunz2013ecology]. most are nocturnal, and rely on echolocation to detect their preys and navigate through space. So far the response of bats to the change in the fire regime has been limited. The only works that research the response of bats to fire divides the environments in high and low intensity fires [@buchalski2013bat], but the response of this taxonomic group to fire is probably more complex than that, since understory fires increases the availability of insects [@lacki2009response], which would be positive for bats, but high intensity basal and canopy fires diminishes roosting sites.

Chiropterans are the only mammals to achieve powered flight, bats have several adaptations for this [@norberg1998morphological]. It is supposed that ancient bats started flying around 50 million years ago [@cooper2012evolution], developing an enlarged hand with a thin membrane between the enlarged fingers, which is very different from the wings of birds. Little is known of the evolution of flight in bats, since the earliest fossils found of these groups were already winged [@gunnell2005fossil; @jepsen1966early]. However wings are not the only adaptation that bats and birds share, they both have higher metabolism and internal temperature than other flightless vertebrates of the same size, their bones are lighter, and have enlarged pectoral muscles that allow them to fly [@norberg1998morphological].

Echolocation is a biological process exclusive to bats, toothed whales, and a few species of birds, it was a termed coined in 1938 by Griffin, who was the first author to thoroughly study the phenomenon [@griffin1941sensory].
The mechanism of echolocation is that the animal producess a sound, an then it bounces against an object, the intensity of the returning sound, plus the time difference between the returning sound at reaching both ears gives information regarding the distance and angle of the detected object [@jones2005echolocation].
Bats use this mechanism to detect their preys [@griffin1960echolocation], avoid obstacles, and even to detect water sources.  Most bat calls are beyond the human hearing range, and they range in frequency from 14,000 to well over 100,000 Hz.
Most species of bats produce very disctint calls, that has been used to detect and differenciate bat species by recording and analysing such calls as in the image below [@fenton1981recognition].

Bats are very important economically in the world. Their most important benefit without a doubt is that they feed on invertebrates and thus they are one of the major natural pest controls for crops, since over two thirds of all bats are obligated insectivorous[@kunz2011ecosystem]. Due to their insect control, only in agriculture, it has been calculated that bats save farmers in the United States 72 dollars/acre [@boyles2011economic], which projects to an economic value of $22.9 billion dollars a year in the United States for the agricultural industry. 
At the same time there are bats that are pollinators of flowers, and there are other frugivorous bats that help spreading seeds [@kunz2011ecosystem]. Bat pollination occurs in about 528 species of angiosperms world-wide. Even though most of north american bats are insectivorous, in arid habitats two families of succulent plants, Agavaceae and Cactaceae, rely on bats to be pollinated. Several of those species are very importance economically in northern and central america and supply food, fiber, tools, soaps, and medicine to the community as well as being the base of the multimillion dollar industry of tequila [@forster2003columnar]. 

The White Nose Syndrome (WNS) is a fatal bat disease produced by the fungus *Pseudogymnoascus destructans*, the origin of its name is the white color left on the infected skin of the muzzle, ears, and wings of bats [@blehert2009bat]. This disease usually causes aberrant behavior of bats during hibernation, including bats prematurely staging at hibernacula entrances, failure of bats to arouse normally in response to disturbance, and diurnal and mid-winter emergence [@langwig2012sociality].

*P. destructans* is capable of living at relatively low temperatures. Thermal performance curves generated for each isolate indicated thermal optima for growth between 12.5 and 15.8°C (54.5 to 60.44 °F) and an upper critical temperature for growth between 19.0 and 19.8°C (66.2 to 67.6°F) [@verant2012temperature], no growth at 24°C (75.2°F) or above [@gargas2009geomyces]. This makes this fungus to grow optimally at the temperatures found in winter bat hibernacula.  Bats are thought to have a lowered immune responses during hibernation torpor [@carey2003mammalian], this may predispose hibernating bats to infection by *P. destructans* [@gargas2009geomyces]. To this date WNS has been estimated to have killed over five million North American bats [@verant2012temperature]. 

WNS is dispersing notoriously trough North America. The first evidence of WNS in bats was detected on February 2006 in New York, and it was documented by a photograph taken at Howes Cave, 52 km west of Albany [@blehert2009bat].  Until 2009, the disease was present only in the northeastern United States [@blehert2009bat], but lately it has been found throughout the midwest and on 2016 in the first case was detected in the west coast in the State of Washington [@USGS2016White]. 
 
Besides WNS, the biggest threat to bats in north america is wind turbines. Every autumn high mortality occur when migrating bats crash into this turbines [@cryan2011wind].
In a review of all multiple mortality events, defined as events where more than 10 bats died at a specific location on the same date, it was estimated that wind turbines have been the cause of more cumulative multiple mortality events than any other reason, followed closely by WNS [@o2016multiple]. From 2003 to 2013 at least 5,626 bats of 27 species in 18 countries where registered to have died in wind turbines [@rodrigues2015guidelines], and this should be only a fraction of the likely mortality, with estimations of 888,000 bat deaths only in north america for the year 2012 [@smallwood2013comparing]. It is also important to note that mortality in not equally distributed among bat species most deaths that happen in wind turbines correspond to migratory species that roost in trees [@arnett2008patterns].

#References