---
title: "Effects of Fire Severity and Post-fire Management on Sensitive Bat Species in Plumas National forest. Project Outline"
author: "Derek Corcoran"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true  
---

#Field work preparation

##Dates:

Leave Columbia Missouri on May the 20th, to reach Quincy on May the 24th or 25th, meetings with interns, Matthew Johnson, and David Arsenault for May the 26th through may the 31st.

Start of sampling June 6th, end of sampling 1st of August.

Estimated number of Sampling Sites 80 sampling sites this season for a total of 129 sampling sites.

##Buy equipemnt

- New Rechargeable Batteries (Ready)
- New Diametrical tapes (Ready)
- New Detectors cables and microphones (to be sent on Monday the 2nd of May)
- New Compact Flash Memory Cards (Ready)

##Set meetings

- Set meeting with Matthew Johnson (date Ready)
- Set meeting with David Arsenault may 27th 3pm Audubon Society.
- Set meeting with Interns (Mail Sent)
- Set meeting with GIS people of the Forest Service in order to get spectral derived layer (Mail Sent)

#Establish sampling regime for monitoring key bat Species (Protocol)

##Background

###Bats

- General information about bats biology, taxonomy, and natural history.

###Why Bats Matter

####Ecosystem services delivered by bats

- General information about bat ecosystem services (pollination, invertebrate control, seed dispersal)
- More detailed information about economic benefits of having bats in north america

####White nose syndrom

- Where white nose syndrome is right now
- Sources on where to find updated information

###Bats in the Plumas National Forest

####Species present in the Plumas National Forest

Small description on each of the species

- *Myotis yumanensis* (Myyu)
- *Myotis californicus* (Myca)
- *Myotis ciliolabrum* (Myci)
- *Myotis volans* (Myvo)
- *Myotis lucifugus* (Mylu)
- *Parastrellus hesperus* (Pahe)
- *Lasiurus blossevillii* (Labo)
- *Myotis evotis* (Myev)
- *Antrozous pallidus*  **(Anpa)**
- *Eptesicus fuscus* (Epfu)
- *Lasionycteris noctivagans* (Lano)
- *Myotis thysanodes* **(Myth)**
- *Tadarida brasiliensis* (Tabr)
- *Lasiurus cinereus* (Laci)
- *Corynorhinus townsendii* **(Coto)**
- *Euderma maculatum* (Euma)
- *Eumops perotis* (Eupe)

#####Product Occupancy map for species studied in the Plumas National Forest

####Bat species of Concern in the Plumas national Forest

Longer description of this species and reasons of why is a species of Concern

- *Antrozous pallidus*  **(Anpa)**
- *Myotis thysanodes* **(Myth)**
- *Corynorhinus townsendii* **(Coto)**

##Site Selection

###The importance in selecting heterogeneus environments

This often improves the representativeness of the sample by reducing sampling error. It can produce a weighted mean that has less variability than the arithmetic mean of a simple random sample of the population.

In computational statistics, stratified sampling is a method of variance reduction when Monte Carlo methods are used to estimate population statistics from a known population.

The reasons to use stratified sampling rather than simple random sampling include[1]

If the population density varies greatly within a region, stratified sampling will ensure that estimates can be made with equal accuracy in different parts of the region, and that comparisons of sub-regions can be made with equal statistical power. For example, in Ontario a survey taken throughout the province might use a larger sampling fraction in the less populated north, since the disparity in population between north and south is so great that a sampling fraction based on the provincial sample as a whole might result in the collection of only a handful of data from the north.

Randomized stratification can also be used to improve population representativeness in a study.

###Classifying Plumas National Forest into different environments

####Layers used to classify the Plumas National Forest

- Altitude (m.a.s.l)
- Burn intensity basal
- Burn intensity canopy
- Burn intensity soil
- Distance to fire edge
- Distance to roads
- Distance to water bodies
- Fire interval
- Vegetation type

####Methods used to classify the Plumas National Forest

- K-means

####Product GIS layer of the Plumas National Forest Classified into 5 different environments

- Raster, and shapefile of the classification of the Plumas National forest

####General Characteristics of the five types of environment

- Graphic output as a classification tree
- Table output as means and standard deviation of each of the variables for each environment type

###Stratified random site-selection

####Product 2000 stratified random points

- 400 points per habitat delivered in KML and shp formats
- Contemplates 200 sampling points per year for the next ten years, 40 points per habitat per year

##Acoustic monitoring

###Advantages and disadvantages of passive acoustic monitoring

- Acoustic bat detectors can be set anywhere
- Acoustic bat detectors can sample for days
- Acoustic bat detectors are not as accurate as mist nets
- Species detection are never 100% accurate

###Setting of the Pettersson D500x bat detector

- Importance of setting the detection time to 3 seconds
- parameter settings
- Set all programs of the detector to the same parameters to avoid field mistakes

###Installing a bat detector in the field

- Explaination of how to deploy the detector in the field

###Field measurements to be taken in the field

- Description of each of the measurements to be taken in the field
- Basal Area
- Canopy cover
- Ground cover

###Using sonobat to automatically classify bat calls into species

####Filter low quality calls

- How to automatically erase bad quality calls in order to diminish sonobat running time

####Classify bat calls

- How to batch-classify the calls for one site

####Interpret the results made by sonobat

- Reading sonobat's output files
- How to see which species are present according to sonobat

####Get sonobat's help to manually vet inconlcusive calls

- How to get sonobat's help to manually vet species that are uncertain to be present

##Interactive tools developed for the interpretation of models

- Shinny app to modify environment and 

#Evaluate occupancy relationships to lanscape features and management for sensitive species

##Introduction

- Describe previous attempts on modeling bat habitats based on landscape variables

###Bats

- Generalities about bats
- Why bats are important to study
- White nose syndrome and bat conservation in North america
- Species of conservation concern in the Plumas National Forest

###Occupancy models as a tool to study the effect of fire on bats

- Advantages of occupancy models
- Why we should use occupancy models to study bats
- Passive acoustic bat surveys and bats

##Methods

###Study Site

- Describe the Sierra Nevada Ecorregion
- Plumas National Forest

###Sampling regime

- Use of Stratified random site-selection to select sampling points
- How the Plumas National Forest was classified in different Strata
- Single session species models

###Analysis

- Use of standardization of variables prior to modeling
- Use of quadratics in models
- Automatic model selection Using AICc

##Results

###Text

###Figures

- Map of predicted occupancy for each species for the plumas national forest

###Tables

- Table of selected models for each species

##Discussion

- Consequences of selected models for bat conservation
- Consequences of selected models for bat management

##Supplementary material

- shinny app to generate species occupancy from variables (gis landscape variables)
- shinny app to generate species occupancy from variables (variables measured in the field)

#Evaluate assosiations between fire affected landscapes and bat occupancy

##Send Manuscript *Bats say: Let California burn*

##Introduction
###Fire in the west coast

- Explain how fire regime has changed
- Explain how fire frequency has been managed
- Describe previous studies made describing how fire affects bats (in particular the one talking about Sierra Nevada)

###Bats

- Generalities about bats
- Why bats are important to study
- White nose syndrome and bat conservation in North america
- Species of conservation concern in the Plumas National Forest

###Occupancy models as a tool to study the effect of fire on bats

- Advantages of occupancy models
- Why we should use occupancy models to study bats
- Passive acoustic bat surveys and bats

##Methods

###Study Site

- Describe the Sierra Nevada Ecorregion
- Plumas National Forest
- Fire History of the Plumas National Forest

###Sampling regime

- Use of Stratified random site-selection to select sampling points
- How the Plumas National Forest was classified in different Strata
- Single session species models

###Analysis

- Use of standardization of variables prior to modeling
- Use of quadratics in models
- Automatic model selection Using AICc
- How to see differences in occupancy in burned vs unburned areas

##Results

###Figures

- Maps of predicted occupancy in different species for the Plumas National Forest
- Box-plots of fitted occupancy for the points sampled in fire vs non-fire for each species

###Tables

- Summary showing if there where possitive, negative and/or quadratic relationships between occupancy and burn intensity for each species
- T-test for every species testing for differences between burned and unburned areas

##Discussion

- Consequences of results to bat management
- Consequences of results and changes in fire patterns over time

##Supplementary material

- Table with models selected for each species
- shinny app to generate species occupancy from variables (Fire related variables)

#Derive Predictive models/maps for key areas for sensitive species

##Improve layers to be used in the models

- Separate Distance to edge of the fire into two variables (Distance from outside and distance from within the fire areas)
- Log-transform distance data (Distance to edge of the fire, Distance to road and Distance to water) prior to standardization

#Get the paper of the DiversityOccupancy package published

- Get the vegetation layers ready to change the data set from bats to birds
- Send manuscript to the Journal of Statistical Software
